wenzhang/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^tinymce/', include('tinymce.urls')),
    url(r'^search', include('haystack.urls')),
    url(r'^',include('yuedu.urls',namespace='index')),

]

yuedu/urls.py
from django.conf.urls import url
from yuedu.views import IndexView,ListView,DetailView,TagsView

urlpatterns = [
    url(r'^list/(?P<type_id>\d+)/(?P<page>\d+)', ListView.as_view(), name='list'),
    url(r'^tag/(?P<tag>[\s\S]*)/(?P<page>\d+)', TagsView.as_view(), name='tag'),
    url(r'^detail/(?P<art_id>\d+)',DetailView.as_view(),name='detail'),
    url(r'^',IndexView.as_view(),name='index'),
]

yuedu/models.py
from django.db import models
from tinymce.models import HTMLField
from db.base_model import BaseModel


class ReadType(BaseModel):

    type = models.CharField(max_length=10,verbose_name='文章类型')
    index = models.SmallIntegerField(default=0,verbose_name='展示顺序')

    def __str__(self):
        return self.type

    class Meta:
        db_table = 'read_type'
        verbose_name = '类型'
        verbose_name_plural = verbose_name

#
# class ReadTypeClass(BaseModel):
#
#     type_class = models.CharField(max_length=10,verbose_name='文章子类型')
#     read_type = models.ForeignKey('ReadType',verbose_name='文章分类')
#
#
#     def __str__(self):
#         return self.type_class
#
#     class Meta:
#         db_table = 'read_type_class'
#         verbose_name = '子分类'
#         verbose_name_plural = verbose_name
#
class ReadTag(BaseModel):
    read_tag = models.CharField(max_length=12,verbose_name='文章标签')

    # article_tag = models.ManyToManyField('Article',verbose_name='文章标签')

    def __str__(self):
        return self.read_tag

    class Meta:
        db_table = 'read_tag'
        verbose_name = '标签'
        verbose_name_plural = verbose_name


class Article(BaseModel):


    detail = HTMLField(blank=True,verbose_name='文章')
    title = models.CharField(max_length=25,verbose_name='文章标题')
    readcount = models.IntegerField(default=0,verbose_name='阅读量')
    read_type = models.ForeignKey('ReadType', verbose_name='文章分类')
    # read_type_class = models.ForeignKey('ReadTypeClass',verbose_name='所属分类')
    read_tag_info = models.ManyToManyField('ReadTag',verbose_name='文章的标签')


    def __str__(self):
        return self.title


    class Meta:
        db_table = 'article'
        verbose_name = '文章'
        verbose_name_plural = verbose_name


class ReadComment(BaseModel):

    comment = models.CharField(max_length=456, blank=True, verbose_name='评论')
    article = models.ForeignKey('Article',verbose_name='所属文章')

    def __str__(self):
        return self.article.title

    class Meta:
        db_table = 'comment'
        verbose_name = '评论'
        verbose_name_plural = verbose_name

yuedu/views.py
from django.shortcuts import render,redirect
from django.core.urlresolvers import reverse
from django.views.generic import View
from django.core.paginator import Paginator
from yuedu.models import ReadType,Article,ReadTag

# Create your views here.



class YueduView(View):

    read_types = ReadType.objects.all().order_by('index')

    news_articles = Article.objects.all().order_by('-create_time')[:8]

    hot_articles = Article.objects.all().order_by('-readcount')[:8]

    hot_tags = ReadTag.objects.all().order_by('-create_time')[:15]




class IndexView(YueduView):
    def get(self,request):

        arts = Article.objects.all().order_by('-create_time')[:20]



        context = {'read_types': YueduView.read_types,
                    'new_articles': YueduView.news_articles,
                    'hot_articles': YueduView.hot_articles,
                    'hot_tags': YueduView.hot_tags,
                    'arts':arts,

                    }

        return render(request,'index.html',context)




class ListView(YueduView):
    def get(self,request,type_id,page):
        try:
            type = ReadType.objects.get(id=type_id)
        except ReadType.DoesNotExsit:
            return redirect(reverse('index:index'))

        types = ReadType.objects.all()

        articles = Article.objects.filter(read_type=type).order_by('-id')

        paginator = Paginator(articles,1)

        try:
            page = int(page)
        except Exception as e:
            page = 1
        if page > paginator.num_pages:
            page = 1


        articles_page = paginator.page(page)

        num_pages = paginator.num_pages

        if num_pages < 5:
            pages = range(1, num_pages + 1)
        elif page <= 3:
            pages = range(1, 6)
        elif num_pages - page <= 2:
            pages = range(num_pages - 4, num_pages + 1)
        else:
            pages = range(page - 2, page + 3)

        context = {
            'read_types': YueduView.read_types,
            'new_articles': YueduView.news_articles,
            'hot_articles': YueduView.hot_articles,
            'hot_tags': YueduView.hot_tags,
            'articles_page':articles_page,
            'type':type,
        }

        return render(request,'list.html',context)



class DetailView(YueduView):
    def get(self,request,art_id):


        try:
            article = Article.objects.get(id=art_id)
        except Article.DoseNotExsit:
            return redirect(reverse('index:index'))


        # try:
        #     previous_art = Article.objects.all(id=art_id).first()
        # except Exception as e:
        #     pass
        #
        #
        #
        # try:
        #     next_art = Article.objects.all(id=art_id).last()
        # except Exception as e:
        #     pass

        same_articles = Article.objects.filter(read_type=article.read_type).exclude(id=art_id).order_by('-create_time')[:10]

        article.readcount += 1
        article.save()

        context = {'read_types': YueduView.read_types,
                   'new_articles': YueduView.news_articles,
                   'hot_articles': YueduView.hot_articles,
                   'hot_tags': YueduView.hot_tags,
                   'article':article,
                   'same_articles':same_articles

                   }

        return render(request,'detail.html',context)



class TagsView(YueduView):
    def get(self,request,tag,page):

        try:
            tags = ReadTag.objects.get(read_tag=tag)
        except ReadTag.DoesNotExsit:

            return redirect(reverse('index:index'))

        # types = ReadType.objects.all()

        articles = Article.objects.filter(read_tag_info=tags).order_by('-id')

        paginator = Paginator(articles, 1)

        try:
            page = int(page)
        except Exception as e:
            page = 1
        if page > paginator.num_pages:
            page = 1

        articles_page = paginator.page(page)

        num_pages = paginator.num_pages

        if num_pages < 5:
            pages = range(1, num_pages + 1)
        elif page <= 3:
            pages = range(1, 6)
        elif num_pages - page <= 2:
            pages = range(num_pages - 4, num_pages + 1)
        else:
            pages = range(page - 2, page + 3)

        context = {
            'read_types': YueduView.read_types,
            'new_articles': YueduView.news_articles,
            'hot_articles': YueduView.hot_articles,
            'hot_tags': YueduView.hot_tags,
            'articles_page': articles_page,
            'tags':tags
        }

        return render(request, 'list2.html', context)

templates/base.html
<!--Cache at 2019-05-06 10:08:12-->
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="zh-CN" lang="zh-CN">
<head>
    {% load staticfiles %}
<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
<meta http-equiv="Content-Language" content="zh-CN">
<meta name="keywords" content="文章阅读">
<meta name="description" content="每天都有经典好文章分享给你">
<title>文章网</title>
<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
<link rel="shortcut icon" href="#">
<link rel="apple-touch-icon" href="#">
<link rel="stylesheet" rev="stylesheet" href="{% static 'css/default.css' %}" type="text/css" media="screen">
<script src="{% static 'js/common.js' %}" type="text/javascript"></script>
</head>
<body>
<div id="wrap">
	<div id="topnav">
		<span></span>
			欢迎访问<a href="#" title="半月文章网">文章网</a>
	</div>
	<div id="head">
		<div class="clear"></div>
	</div>


	<div id="nav">


		<ul class="nav1">

			<li class="navli1"><a href="/index" title="文章网">首页</a></li>

			{% for read_type in read_types %}

			<li class="navli1"><a href="/list/{{ read_type.id }}/1" title="文章">{{ read_type.type }}</a>
			{% endfor %}
				<!--<ul class="nav2">-->
                    <!--<li><a href="/list-20-0.html" title="爱情文章">爱情文章</a></li>-->
                    <!--<li><a href="/list-21-0.html" title="亲情文章">亲情文章</a></li>-->
                <!--</ul>-->
		</ul>
	</div>



	<nav id="navs-wrap">
		<div id="logos">
			<h1><a href="/index" title="半月文章网">文章网</a></h1>
		</div>
		<div class="menu-icon">导航</div>

		<ul id="navs" class="menu">
			<li class="searchBtn"><a name="search">本站搜索</a></li>
			{% for read_type in read_types %}
			<li><a href="/list/{{ read_type.id }}/1" title="{{ read_type.type }}">{{ read_type.type }}</a></li>
 			{% endfor %}
        </ul>
	</nav>

{% block body %}{% endblock body %}


	<div id="right">
		<dl id="ss">



			<form method='get' action="/search" target="_blank">
                <input type="text" name="q" id="edtSearch" class="text" autocomplete="off" placeholder="请输入关键词" x-webkit-speech=""/>
                <input type="submit" id="btnPost" value="查询"/>
			</form>



			<div class="clear"></div>



		</dl>
		<dl class="function">
			<dd class="function_c">
				<div><script src="{% static 'js/thea2.js' %}"></script></div>
			</dd>
		</dl>
		<dl class="function">
			<dt class="function_t">最新文章</dt>
			<dd class="function_c">
				{% for new_article in new_articles %}
				<ul>
                    <li><a href="/detail/{{ new_article.id }}" title="{{ new_article.title }}">{{ new_article.title }}</a></li>
                </ul>
				{% endfor %}
			</dd>
		</dl>



		<dl class="function">
			<dd class="function_c">
				<div>
					<script src="{% static 'js/thea3.js' %}"></script>
				</div>
			</dd>
		</dl>


		<dl class="function">
			<dt class="function_t">热门文章</dt>
			<dd class="function_c">

				<ul>
					{% for hot_article in hot_articles %}
                    <li><a href="/detail/{{ hot_article.id }}" title="{{ hot_article.title }}">{{ hot_article.title }}</a></li>
					{% endfor %}
                </ul>

			</dd>
		</dl>




		<dl class="function">
			<dd class="function_c">
				<div><script src="{% static 'js/thea4.js' %}"></script></div>
			</dd>
		</dl>
		<dl class="function" id="divTags">
			<dt class="function_t">热门标签</dt>
			<dd class="function_c">
				<ul>
                    <li class="tag-name">
						{% for hot_tag in hot_tags %}
                        <a href="/tag/{{ hot_tag.read_tag }}/1" title="{{ hot_tag.read_tag }}">{{ hot_tag.read_tag }}
						{% endfor %}
                            <!--<span class="tag-count"></span>-->
                        </a>
                    </li>
                </ul>
			</dd>
		</dl>





		<!--<dl class="function">-->
			<!--<dd class="function_c">-->
				<!--<div>-->
					<!--<script src="{% static 'js/thea5.js' %}"></script>-->
				<!--</div>-->
			<!--</dd>-->
		<!--</dl>-->
		<!--<dl class="function">-->
			<!--<dt class="function_t">随机文章阅读</dt>-->
			<!--<dd class="function_c">-->
				<!--<ul>-->
                    <!--<li><a href="/article-95-211680-0.html" title="“我 想 你 没 睡”">“我 想 你 没 睡” (9)</a></li>-->
                <!--</ul>-->
			<!--</dd>-->
		<!--</dl>-->



	</div>






	<div class="clear"></div>
	<div id="links">
		<ul>
            <li><strong>友情链接</strong>：</li>
            <li><a href="http://www.osimg.com" title="osimg" target="_blank">osimg绅士网站</a></li>
            <div class="clear"></div>
        </ul>
	</div>


	<script type="text/javascript" src="{% static 'js/jquery.min.js' %}"></script>
	<script type="text/javascript" src="{% static 'js/script.js' %}"></script>
	<a href="#0" class="cd-top">Top</a>
	<div class="footer" id="footer">
		<p>© 2018 。。。。。  | <a href="#" target="_blank" title="关于我们">关于我们</a> | <a href="/contact.html" target="_blank" title="联系方式">联系方式</a> | <a href="/tags/" target="_blank" title="话题列表">文章标签</a> | <a href="/map.html" target="_blank" title="网站地图">网站地图</a></p>
		<p id="BY-NC-ND">本站所有文章内容均来源于互联网，版权归原作者所有，所有文章内容观点与本站立场无关，如不慎侵犯了您的权益，请联系我们，我们将在第一时间处理！</p>
	</div>

	<div id="simplemodal-container"></div>

	<div id="searchbar">
		<p>全站搜索</p>
		<form onsubmit="return checkSearchForm()" method="post" name="searchform" action="/e/search/index.php">
			<input type="hidden" value="title" name="show"><input type="hidden" value="1" name="tempid"><input type="hidden" value="news" name="tbname"><input name="mid" value="1" type="hidden"><input name="dopost" value="search" type="hidden"><input type="text" name="keyboard" id="edtSearch" class="text" value="输入搜索关键词" onblur="if($(this).val() == ''){$(this).val('输入搜索关键词');}" onfocus="if($(this).val() == '输入搜索关键词'){$(this).val('');}" x-webkit-speech=""/><input type="submit" id="btnPost" name="submit" class="submit" value="搜索"/>
		</form>
	</div>
</div>

<script src="{% static 'js/inbody.js' %}" type="text/javascript"></script>

</body>
</html>

templates/index.html
{% extends 'base.html' %}{% load staticfiles %}{% block body %}	<div id="left">		<div id="lieb">			{% for art in arts %}			<dl>				<dt><span><a target="_blank" href="/list/{{ art.id }}/1" title="阅读更多{{ art.read_type }}的文章">{{ art.read_type }}</a></span>				<h2><a target="_blank" href="/detail/{{ art.id }}" title="{{ art.title }}">{{ art.title }}</a></h2>				</dt>				<dd><div id="zi1"><p><a target="_blank" href="/detail/{{ art_id }}">{{ art.detail|safe }}</a></p></div>				<p class="tags">{{ art.create_time }} | 阅读：<span>{{ art.readcount }}</span> | 标签:&nbsp;					{% for tag in art.read_tag_info.all %}					<a href='/tag/{{ tag.read_tag }}/1' target='_blank' rel='tag'>{{ tag.read_tag }}</a>					{% endfor %}				</p>				</dd>				<div class="clear"></div>			</dl>			{% endfor %}s			<div class="indexlb"></div>		</div>	</div>{% endblock body %}

templates/list.html
{% extends 'base.html' %}


{% block body %}
	<div id="left">
		<div id="place">
			<strong>你的位置：</strong>
            <a href="/index" title="半月文章网">首页</a>&nbsp;>&nbsp;
            <a href="/list/{{ type.id }}/1" title="{{ type.type }}">{{ type.type }}</a>
		</div>
		<!--<ul class="subnav">-->
            <!--<li><a href="/list-20-0.html" title="爱情文章">爱情文章</a></li>-->
            <!--<li><a href="/list-21-0.html" title="亲情文章">亲情文章</a></li><-->
            <!--li><a href="/list-22-0.html" title="友情文章">友情文章</a></li><-->
            <!--li><a href="/list-23-0.html" title="心情文章">心情文章</a></li>-->
            <!--<li><a href="/list-24-0.html" title="励志文章">励志文章</a></li>-->
            <!--<li><a href="/list-25-0.html" title="节日文章">节日文章</a></li>-->
            <!--<li><a href="/list-26-0.html" title="校园文章">校园文章</a></li>-->
            <!--<li><a href="/list-27-0.html" title="百家杂谈">百家杂谈</a></li>-->
        <!--</ul>-->



		<div id="lieb">
            {% for article in articles_page  %}
			<dl>

	            <dt>
                    <span><a target="_blank" href="/detail/{{ article.id }}" title="的文章">节日文章</a></span>
	            <h2>
                    <a target="_blank" href="/detail/{{ article.id }} " title="{{ article.title }}">{{ article.title }}</a>
                </h2>
	            </dt>
	        <dd>
	            <div id="zi1">
		            <p><a target="_blank" href="#">{{ article.detail|safe }}</a></p>
	            </div>

	            <p class="tags">{{ article.create_time }} | 阅读：<span>{{ article.readcount }}</span> | 标签：
					{% for tag in article.read_tag_info.all %}
                    <a href='/tag/{{ tag.read_tag }}/1' target='_blank' title='{{ tag.read_tag }}' rel='tag'>{{ tag.read_tag }}</a>&nbsp;
					{% endfor %}
	        </dd>
                <div class="clear"></div>

            </dl>
            {% endfor %}




			<dl class="pagebar">

               {% if articles_page.has_previous %}
				<a href="{% url 'index:list' type.id articles_page.previous_page_number %}">上一页></a>
				{% endif %}
				{% for pindex in articles_page.paginator.page_range %}

					{% if pindex == articles_page.number %}
						<a href="{% url 'index:list' type.id pindex %}" class="active">{{ pindex }}</a>
					{% else %}
						<a href="{% url 'index:list' type.id pindex %}">{{ pindex }}</a>
					{% endif %}
				{% endfor %}
				{% if articles_page.has_next %}
				<a href="{% url 'index:list' type.id articles_page.next_page_number %}">下一页></a>
				{% endif %}
            </dl>
		</div>
	</div>



{% endblock body %}

templates/list2.html
{% extends 'base.html' %}


{% block body %}
	<div id="left">
		<div id="place">
			<strong>你的位置：</strong>
            <a href="/index" title="半月文章网">首页</a>&nbsp;>&nbsp;
            <a href="/tag/{{ tags.read_tag }}/1" title="{{ tags.read_tag }}">{{ tags.read_tag }}</a>
		</div>
		<!--<ul class="subnav">-->
            <!--<li><a href="/list-20-0.html" title="爱情文章">爱情文章</a></li>-->
            <!--<li><a href="/list-21-0.html" title="亲情文章">亲情文章</a></li><-->
            <!--li><a href="/list-22-0.html" title="友情文章">友情文章</a></li><-->
            <!--li><a href="/list-23-0.html" title="心情文章">心情文章</a></li>-->
            <!--<li><a href="/list-24-0.html" title="励志文章">励志文章</a></li>-->
            <!--<li><a href="/list-25-0.html" title="节日文章">节日文章</a></li>-->
            <!--<li><a href="/list-26-0.html" title="校园文章">校园文章</a></li>-->
            <!--<li><a href="/list-27-0.html" title="百家杂谈">百家杂谈</a></li>-->
        <!--</ul>-->



		<div id="lieb">
            {% for article in articles_page  %}
			<dl>

	            <dt>
                    <span><a target="_blank" href="/detail/{{ article.id }}" title="的文章">节日文章</a></span>
	            <h2>
                    <a target="_blank" href="/detail/{{ article.id }} " title="{{ article.title }}">{{ article.title }}</a>
                </h2>
	            </dt>
	        <dd>
	            <div id="zi1">
		            <p><a target="_blank" href="#">{{ article.detail|safe }}</a></p>
	            </div>

	            <p class="tags">{{ article.create_time }} | 阅读：<span>{{ article.readcount }}</span> | 标签：
					{% for tag in article.read_tag_info.all %}
                    <a href="/tag/{{ tag.read_tag }}/1" target='_blank' title='{{ tag.read_tag }}' rel='tag'>{{ tag.read_tag }}</a>&nbsp;
					{% endfor %}

	        </dd>
                <div class="clear"></div>

            </dl>
            {% endfor %}




			<dl class="pagebar">

               {% if articles_page.has_previous %}
				<a href="{% url 'index:tag' tags.read_tag articles_page.previous_page_number %}">上一页></a>
				{% endif %}
				{% for pindex in articles_page.paginator.page_range %}

					{% if pindex == articles_page.number %}
						<a href="{% url 'index:tag' tags.read_tag pindex %}" class="active">{{ pindex }}</a>
					{% else %}
						<a href="{% url 'index:tag' tags.read_tag pindex %}">{{ pindex }}</a>
					{% endif %}
				{% endfor %}
				{% if articles_page.has_next %}
				<a href="{% url 'index:tag' tags.read_tag articles_page.next_page_number %}">下一页></a>
				{% endif %}
            </dl>
		</div>
	</div>



{% endblock body %}

templates/search/search.html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="zh-CN" lang="zh-CN">
<head>
    {% load staticfiles %}
<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
<meta http-equiv="Content-Language" content="zh-CN">
<meta name="keywords" content="经典文章阅读">
<meta name="description" content="每天都有经典好文章分享给你。">
<title>文章网</title>
<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
<link rel="shortcut icon" href="/style/images/favicon.ico">
<link rel="apple-touch-icon" href="/style/images/favicon_touch.png">
<link rel="stylesheet" rev="stylesheet" href="{% static 'css/default.css' %}" type="text/css" media="screen">
<script src="{% static 'js/common.js' %}" type="text/javascript"></script>
</head>
<body>

<div id="wrap">
	<div id="topnav">
		<span></span>
			欢迎访问<a href="#" title="半月文章网">文章网</a>
			</div>
		<div id="head">
			<div class="clear"></div>
		</div>


	<div id="left">
		<div id="place">
			<strong>你的位置：</strong>
            <a href="/index" title="文章网">首页</a>&nbsp;>&nbsp;
            <a href="#" title="{{ query }}">{{ query }}</a>
		</div>



		<div id="lieb">
            {% for item in page %}
			<dl>

	            <dt>
                    <span><a target="_blank" href="/list/{{ item.object.read_type.id }}/1" title="{{ item.object.read_type.type }}">{{ item.object.read_type.type }}</a></span>
	            <h2>
                    <a target="_blank" href="/detail/{{ item.object.id }} " title="{{ item.object.title }}">{{ item.object.title }}</a>
                </h2>
	            </dt>
	        <dd>
	            <div id="zi1">
		            <p><a target="_blank" href="#">{{ item.object.detail|safe }}</a></p>
	            </div>

	            <p class="tags">{{ item.object.create_time }} | 阅读：<span>{{ item.object.readcount }}</span> | 标签：
					{% for tag in item.object.read_tag_info.all %}
                    <a href='/tag/{{ tag.read_tag }}/1' target='_blank' title='{{ tag.read_tag }}' rel='tag'>{{ tag.read_tag }}</a>&nbsp;
					{% endfor %}
	        </dd>
                <div class="clear"></div>

            </dl>
            {% endfor %}




			<dl class="pagebar">

               {% if page.has_previous %}
				<a href="/search?q={{ query }}&page={{ page.previous_page_number }}">上一页></a>
				{% endif %}
				{% for pindex in　paginator.page_range %}

					{% if pindex == page.number %}
						<a href="/search?q={{ query }}&page={{ pindex }}" class="active">{{ pindex }}</a>
					{% else %}
						<a href="/search?q={{ query }}&page={{ pindex }}">{{ pindex }}</a>
					{% endif %}
				{% endfor %}
				{% if page.has_next %}
				<a href="{% url 'index:list' type.id articles_page.next_page_number %}">下一页></a>
				{% endif %}
            </dl>
		</div>
	</div>

	<div id="right">
		<dl id="ss">

		<form method='get' action="/search" target="_blank">
			<input type="text" name="q" id="edtSearch" class="text" autocomplete="off" placeholder="请输入关键词" x-webkit-speech=""/>
			<input type="submit" id="btnPost" value="查询"/>
		</form>

	</div>



			<div class="clear"></div>

	<div class="clear"></div>
	<div id="links">
		<ul>
            <li><strong>友情链接</strong>：</li>
            <li><a href="http://www.osimg.com" title="osimg" target="_blank">osimg绅士网站</a></li>
            <div class="clear"></div>
        </ul>
	</div>


	<script type="text/javascript" src="{% static 'js/jquery.min.js' %}"></script>
	<script type="text/javascript" src="{% static 'js/script.js' %}"></script>
	<a href="#0" class="cd-top">Top</a>
	<div class="footer" id="footer">
		<p>© 2018 半月文章网 www.byjpeixun.com  | <a href="#" target="_blank" title="关于我们">关于我们</a> | <a href="/contact.html" target="_blank" title="联系方式">联系方式</a> | <a href="/tags/" target="_blank" title="话题列表">文章标签</a> | <a href="/map.html" target="_blank" title="网站地图">网站地图</a></p>
		<p id="BY-NC-ND">本站所有文章内容均来源于互联网，版权归原作者所有，所有文章内容观点与本站立场无关，如不慎侵犯了您的权益，请联系我们，我们将在第一时间处理！</p>
	</div>

	<div id="simplemodal-container"></div>

	<div id="searchbar">
		<p>全站搜索</p>
		<form onsubmit="return checkSearchForm()" method="post" name="searchform" action="/e/search/index.php">
			<input type="hidden" value="title" name="show"><input type="hidden" value="1" name="tempid"><input type="hidden" value="news" name="tbname"><input name="mid" value="1" type="hidden"><input name="dopost" value="search" type="hidden"><input type="text" name="keyboard" id="edtSearch" class="text" value="输入搜索关键词" onblur="if($(this).val() == ''){$(this).val('输入搜索关键词');}" onfocus="if($(this).val() == '输入搜索关键词'){$(this).val('');}" x-webkit-speech=""/><input type="submit" id="btnPost" name="submit" class="submit" value="搜索"/>
		</form>
	</div>
</div>

<script src="{% static 'js/inbody.js' %}" type="text/javascript"></script>

</body>
</html>